"""Type stubs for the compiled `_fovea_mv` extension."""

from __future__ import annotations

from typing import Iterator, Optional, Sequence, Union

import numpy as np
from numpy.typing import NDArray

def core_version() -> str: ...

class RegionMask:
    def __init__(self, x0: int, y0: int, x1: int, y1: int) -> None: ...
    @property
    def x0(self) -> int: ...
    @property
    def y0(self) -> int: ...
    @property
    def x1(self) -> int: ...
    @property
    def y1(self) -> int: ...

class MotionTrigger:
    def __init__(
        self,
        energy_threshold: int,
        *,
        min_duration_ms: int = 0,
        mask: Optional[RegionMask] = None,
    ) -> None: ...
    @classmethod
    def per_mb(
        cls,
        threshold_per_mb: float,
        *,
        min_duration_ms: int = 0,
        mask: Optional[RegionMask] = None,
    ) -> MotionTrigger: ...

class IntervalTrigger:
    def __init__(self, max_gap_ms: int) -> None: ...

class SceneChangeTrigger:
    def __init__(self, intra_block_ratio_threshold: float) -> None: ...

Trigger = Union[MotionTrigger, IntervalTrigger, SceneChangeTrigger]

class VideoInfo:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def frame_rate(self) -> float: ...
    @property
    def duration_s(self) -> Optional[float]: ...

class Event:
    @property
    def timestamp_s(self) -> float: ...
    @property
    def ts_us(self) -> int: ...
    @property
    def frame_type(self) -> str: ...
    @property
    def trigger_name(self) -> str: ...
    @property
    def energy(self) -> int: ...
    @property
    def intra_ratio(self) -> float: ...
    @property
    def mv_count(self) -> int: ...
    def decode(self) -> NDArray[np.uint8]: ...

class EventIterator:
    def __iter__(self) -> EventIterator: ...
    def __next__(self) -> Event: ...

class Stream:
    def __init__(self, path: str, *, fast_decode: bool = False) -> None: ...
    @classmethod
    def from_file(cls, path: str, *, fast_decode: bool = False) -> Stream: ...
    def info(self) -> VideoInfo: ...
    def events(self, triggers: Sequence[Trigger]) -> EventIterator: ...
