//! Step 2.6 golden test.
//!
//! Runs MV extraction on a tiny deterministic clip committed to the repo
//! (`tests/fixtures/golden.mp4`, 320×240, 10 frames at 10fps generated by
//! `ffmpeg -f lavfi -i testsrc ... -c:v libx264 -preset veryslow ...`).
//!
//! The clip is small enough to commit; its content is deterministic, so
//! exact MV counts and frame-type sequence should not drift across machines.
//! If FFmpeg's libavcodec changes behavior, this test surfaces it.

use std::path::PathBuf;

use fovea_mv_core::{motion_energy, FrameType};
use fovea_mv_stream::FfmpegSource;

fn fixture_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/golden.mp4");
    p
}

#[test]
fn golden_clip_extraction() {
    let path = fixture_path();
    assert!(path.exists(), "fixture missing at {path:?}");

    let mut src = FfmpegSource::open_file(&path).expect("open golden");
    let info = src.info().clone();
    assert_eq!(info.width, 320);
    assert_eq!(info.height, 240);
    let expected_total_mb = 320u32.div_ceil(16) * 240u32.div_ceil(16); // 20 * 15 = 300

    let mut frames: Vec<(FrameType, u32, u32, u64)> = Vec::new(); // (type, mv_count, intra_count, energy)
    while let Some(pkt) = src.next_packet().expect("decode") {
        assert_eq!(pkt.total_mb, expected_total_mb);
        frames.push((
            pkt.frame_type,
            pkt.mvs.len() as u32,
            pkt.intra_count,
            motion_energy(&pkt.mvs),
        ));
    }

    println!("frame count: {}", frames.len());
    for (i, (ft, mv_n, intra, e)) in frames.iter().enumerate() {
        println!("  [{i}] {ft} mv_count={mv_n} intra={intra} energy={e}");
    }

    assert_eq!(frames.len(), 10, "expected 10 frames");

    // First frame must be I; intra_ratio == 1.0.
    assert_eq!(frames[0].0, FrameType::I, "frame 0 should be I");
    assert_eq!(frames[0].1, 0, "I-frame must have 0 MVs");
    assert_eq!(frames[0].2, expected_total_mb, "I-frame intra_count == total_mb");
    assert_eq!(frames[0].3, 0, "I-frame energy must be 0");

    // At least one inter-coded frame must exist with MVs and non-zero energy.
    let inter_with_motion = frames
        .iter()
        .skip(1)
        .filter(|(ft, mv_n, _, e)| matches!(ft, FrameType::P | FrameType::B) && *mv_n > 0 && *e > 0)
        .count();
    assert!(
        inter_with_motion >= 1,
        "expected at least one inter frame with motion"
    );

    // No frame may have intra_count > total_mb (invariant).
    for (i, (_, _, intra, _)) in frames.iter().enumerate() {
        assert!(
            *intra <= expected_total_mb,
            "frame {i} intra_count {intra} > total_mb {expected_total_mb}"
        );
    }
}
